dockerapp:
  build: .
  command: php-fpm --allow-to-run-as-root
  volumes:
    - ./php/php.ini:/usr/local/etc/php/php.ini
    - ..:/var/www/project
  links:
   - mysql
mysql:
  command: mysqld --user=root --verbose
  image: mysql
  volumes:
    - ../.mysql:/var/lib/mysql
  environment:
    MYSQL_DATABASE: project
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
nginx:
  image: nginx:1.9
  volumes:
    - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    - ..:/var/www/project
  ports:
   - "80:80"
  links:
   - dockerapp